/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#b9f61d',
        'primary-fixed': '#b2faa9',
        'tertiary-fixed': '#10eafe',
        'on-background': '#2c2f30',
        'on-secondary-fixed': '#324600',
        tertiary: '#00656f',
        'surface-dim': '#d1d5d7',
        'primary-dim': '#185c1e',
        'primary-fixed-dim': '#a4eb9c',
        error: '#b02500',
        'on-tertiary-fixed-variant': '#005c64',
        secondary: '#496400',
        'secondary-fixed-dim': '#ace700',
        'on-surface-variant': '#595c5d',
        'on-primary-fixed-variant': '#2a6c2c',
        'surface-tint': '#266829',
        'on-primary-fixed': '#054e12',
        'on-secondary-fixed-variant': '#496400',
        'inverse-on-surface': '#9b9d9e',
        'surface-container-highest': '#dadddf',
        'on-tertiary-fixed': '#003d43',
        'tertiary-dim': '#005861',
        'tertiary-container': '#10eafe',
        'on-secondary-container': '#415a00',
        outline: '#757778',
        'surface-variant': '#dadddf',
        'primary-container': '#b2faa9',
        background: '#f5f6f7',
        'tertiary-fixed-dim': '#00dbee',
        'surface-container-low': '#eff1f2',
        'on-primary': '#d1ffc8',
        'on-error-container': '#520c00',
        'on-tertiary-container': '#005159',
        'on-primary-container': '#1f6223',
        'error-dim': '#b92902',
        'on-secondary': '#deff97',
        'on-error': '#ffefec',
        surface: '#f5f6f7',
        'surface-container-lowest': '#ffffff',
        'error-container': '#f95630',
        'surface-container': '#e6e8ea',
        primary: '#266829',
        'on-surface': '#2c2f30',
        'inverse-primary': '#b2faa9',
        'secondary-fixed': '#b9f61d',
        'on-tertiary': '#d4f9ff',
        'inverse-surface': '#0c0f10',
        'secondary-dim': '#3f5700',
        'outline-variant': '#abadae',
        'surface-container-high': '#e0e3e4',
        'surface-bright': '#f5f6f7',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },
  plugins: [],
};
